name: Cypress Tests

on:
  push:
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:14.2.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Cypress tests
        run: npx cypress run --spec "e2e/Tests/demoblaze.cy.js"
